### ISSUE TITLE
How are refs handled?

### ISSUE THREAD

**Issue by AsaAyers** [ekosz/redux-falcor#1]
Does the state hold refs, or do they get expanded automatically?

http://netflix.github.io/falcor/documentation/jsongraph.html

```js
{
    todosById: {
        "44": {
            name: "get milk from corner store",
            done: false,
            prerequisites: [{ $type: "ref", value: ["todosById", 54] }]
        },
        "54": {
            name: "withdraw money from ATM",
            done: false,
            prerequisites: []
        }
    },
    todos: [
        { $type: "ref", value: ["todosById", 44] },
        { $type: "ref", value: ["todosById", 54] }
    ]
};
```

If this is the data in your model. would `state.entities.todos[0]` be ` { $type: "ref", value: ["todosById", 44] }` or `{
            name: "get milk from corner store",
            done: false,
            prerequisites: [{ $type: "ref", value: ["todosById", 54] }]
        },`

**Comment by ekosz** [comment]
The references that you define in your router will indeed be expanded out. The result that comes back from your Falcor query will always match the path you send. 

So it really depends on how you query that data. If you where to query using:

```js
state.dispatch(retrievePath('todos[0]["name","done"]'))
```

The entities would look like (when it resolves)

```js
{
  todos: { 
    0: { 
      done: false, 
      name: 'get milk from corner store' 
    } 
}
```

If you were to query the data like this:

```js
state.dispatch(retrievePath('todos[0]["prerequisites"][0]["name"]'))
```

The entities would look like (when it resolves)

```js
{
  todos: { 
    0: {
      prerequisites: {
        0: {
          name: "withdraw money from ATM",
        }
      }
    }
  }
}
```

I've added another test to shows how this works [here](https://github.com/ekosz/redux-falcor/blob/7c6341a79469262802e14d8e81c17e92a2a1c0a6/test/middleware.spec.js#L56-L87). 

Does this answer your question?

**Comment by AsaAyers** [comment]
oh! now it just clicked. It's really a 2-layer cache. The Faclor model holds a cache of what we know from the server (this includes references) and `state.entities` only holds a cache of what you have asked the Falcor model for.

It doesn't look like `redux-falcor` has any methods of changing data in the model yet. Do you have a plan on how `store.entities` can be kept accurate when those are added?

**Comment by ekosz** [comment]
@AsaAyers Haha, yeah I was just thinking of that in the shower. I probably shouldn't have made this 1.0 until I implemented `set` and `call` at the very least huh?

I'll work on that today, but the goal would be to never interact with the falcor model directly, other than setting it up. Everything thing else should happen through an action.

What I'm thinking of would be something like:

```js
store.dispatch(setPath('my["email"]', 'baz@bar.com'))

store.dispatch(callPath(['todos', 'add'], ["pick up some eggs"], [["name"], ["done"]]))
```

**Comment by AsaAyers** [comment]
There are probably many problems with this that I haven't thought through:

Another potential strategy would be to watch the model for changes and use[`Model.onChange()`](http://netflix.github.io/falcor/doc/Model.html#~onChange) and [`Model.getCache()`](http://netflix.github.io/falcor/doc/Model.html#getCache) to push the data into the store. Then the Redux store is never stale, but it would introduce the overhead of expanding all of the references, so your Redux store would have duplicate data.

I'd still dispatch actions to manipulate the store since that's The Redux Way.

I have also made the early `1.0.0` mistake. Recently I've been starting projects at `0.0.1` instead :) There is a pretty active Redux channel on [Slack](http://www.reactiflux.com/). You might get some good input there, and you can message me directly if you'd like to chat.

**Comment by ekosz** [comment]
Yep I was just thinking about using `getCache` instead of my current update strategy. I just pushed up the `setPath` action as a first attempt.

Thanks for the feedback so far! I'll be sure to jump in the channel some point soon.
