### ISSUE TITLE
Guide/Example

### ISSUE THREAD

**Issue by kennetpostigo** [ekosz/redux-falcor#10]
Hello,

Im new to falcor, but use redux and react all the time, I really want to use this library as falcor + redux make for an amazing combination in my head. The README.md was great but I was wondering if there are any example applications that demonstrate this library `v3.0.0` in action. Hopefully there is and I would greatly appreciate it if you could direct me to its location please.

Great job on the library, keep it up!

**Comment by bartonhammond** [comment]
+1

**Comment by ekosz** [comment]
Hey all,

I really want to write an example app as soon as I can, but right now I'm in crunch mode at work. I haven't forgotten about this and will do it as soon as I can. Do you know of examples of great examples I can riff off of? Is the Todo app still in vouge?

Also if anyone else wants to take a crack at this I'm happy to review any PRs and give suggestions.

**Comment by bartonhammond** [comment]
I'll take a crack at creating an example today.  When I started with Redux I had a simple "Counter" example.  I still have that starting point example somewhere on my system so I'll start with that (hopefully).  It's a react-native example.

**Comment by bartonhammond** [comment]
Well that was disappointing - Falcor doesn't work w/ React Native.  Sorry - no example from me.

**Comment by chileung** [comment]
@ekosz Hello, I'm new too. hopefully want an example as soon as possible. Thx ~

**Comment by chileung** [comment]
Well I'll take some time to create an todo example recently.

**Comment by kevnk** [comment]
Anyone here have a working example? I seem to have it all plugged in as it shows in the README.md but nothing is happening

**Comment by kevnk** [comment]
I have a separate host for requesting the data so I needed to set the `source` option in my falcor model

```babel
import {Model} from 'falcor';
import HttpDataSource from 'falcor-http-datasource';

// The falcor model that redux-falcor will query
const falcor = new Model({
    source: new HttpDataSource('192.168.99.100:9090/model.json'),
    cache: {
        // Optional data here
    }
});
```
