### ISSUE TITLE
How does release 3.0.0 square w/ "fighting against the tide here"

### ISSUE THREAD

**Issue by bartonhammond** [ekosz/redux-falcor#13]
https://github.com/Netflix/falcor/issues/572#issuecomment-164896525

>@trxcllnt That looks great! Unfortunately I have yet to learn RxJS, but it's on my todo list. Ultimately I think I'm fighting against the tide here. It seems (at least to me) that redux and falcor are just a tad too different to really connect on a meaningful level. Which is a real pain as I've based my entire stack on those two technologies haha.

**Comment by ekosz** [comment]
@bartonhammond Before 3.0.0 redux was "pulling" from falcor new state changes. This lead the two to desync often. Now in 3.0.0 falcor "pushes" state changes to redux, making sure the two data stores are always in sync.

**Comment by bartonhammond** [comment]
Yes it does answer - I was wondering what that "status" was.
