### ISSUE TITLE
How does this relate to actions and reducers?

### ISSUE THREAD

**Issue by talarari** [ekosz/redux-falcor#15]
if i'm understanding this correctly basically the falcor model is the state and it has one big reducer to return the whole state as changed when anything happens.

so my actions should set to the falcor model and there's no need to write reducers?
isn't this basically the same as having a mutable state ?

**Comment by RobertButera** [comment]
Someone who knows more should correct me if I'm wrong, but my understanding is that what redux-falcor does is project the falcor cache onto the redux store.  It does not mutate the redux state.

The falcor cache itself is mutable.  Redux falcor watches for changes on the falcor cache.  When it detects a change it creates a new version (from the root) of the object that will be stored in the redux store and replaces the existing version.

Ideally redux-falcor would be smart enough to only replace the minimum amount of the redux store on each change.  Hopefully this is planned for a future version.

**Comment by talarari** [comment]
And regarding actions and reducers, I'm I correct saying that actions would only set state to the falcor model and no reducers are needed?

**Comment by ekosz** [comment]
Hey @talarari 

None of your actions should change the falcor state, that should all be handled by `redux-falcor`. You should be querying falcor and then reading the redux state for the results of the query. I'm not sure what you mean by multiple state. You should only ever be reading from the state and firing off queries, never writing to the redux state yourself.

@RobertButera is correct where I currently swap the entire falcor state tree out, but I do plan to try and optimize that in a later release.

**Comment by talarari** [comment]
Sorry maybe I wasn't clear when I said setting state to falcor model . I ment calling setValue on the model to perform a write to the falcor model.

**Comment by ekosz** [comment]
Oh, sorry. Yes, that's all you need to do. 

application calls `setValue` 
--> falcor updates model (**async**)
--> falcor triggers onChange
--> redux-falcor constructs new state (**async**)
--> redux-falcor updates redux state
--> application reads from new state
