### ISSUE TITLE
Falcor Mutability vs Redux Immutability

### ISSUE THREAD

**Issue by sburgess8** [ekosz/redux-falcor#16]
I am investigating using redux-falcor for a project. My concern relates to the mutability of Falcor vs the immutability of Redux. I don't have a complete understanding of the unidirectional flow in redux-falcor yet, but my impression is that a) they're both referencing the same Redux store and b) Falcor calls to get state are called from any component, as would be done in Redux. State from Falcor is not duplicated in Redux, but access to Falcor is wrapped with redux-falcor. Regular Redux application state is stored separately and uses a different subscription in the react-redux {connect} method by omitting the Falcor wrapper.

Falcor asynchronously gets the information from the cache and if it's not available there it calls to the server. When it calls to the server and new state is updated, redux-falcor applies the FP principle of reducers to create an entirely new state tree with the new info. This triggers Redux update state. Then through the separate Falcor prop which is bundled with Redux, that information is pushed to the rendering components that subscribed to it with react-redux {connect}. 

Redux is using FP with immutable state and recreating a new state on each change. On the other hand, some of the "benefit" of Falcor is its mutability, thus allowing for minimal processing demands. What I don't understand is where the real inefficiency lies.

Is the current inefficiency increased processing demands on the client side to recreate the Falcor state tree? Do all Falcor routes end up making a call to the server whether the info is in the client side cache or not? Do you still have the benefit of client-side caching with Falcor in redux-falcor? I would assume yes, but I'd just like to make sure. At what scale would the inefficiency of recreating the state tree affect performance? If it were being used on a large scale, would this be a crucial inefficiency on the scale of seconds? Would you say that redux-falcor is production ready?

I appreciate all the work you've put into this bleeding edge tech. I'm wondering (and hoping it's not the case) whether the mutability of Falcor and immutability of Redux are at some level fundamentally incompatible and that by using both libraries you lose the respective efficiencies of each. Sorry if I have any misunderstandings in this question. I'm hoping a short answer will be able to clear this up for me. Thank you.

**Comment by przeor** [comment]
@sburgess8 please send me a line to kamil@przeorski.pl - I am also evaluating this option, it's worth to get in touch.

**Comment by sburgess8** [comment]
Thank you, we are trying another options.

**Comment by c0** [comment]
I'm interested in this as well. From what I can gather, the redux store is a *snapshot* of falcor's model cache. Components then render off this immutable state.

What alternatives are you considering?

**Comment by ekosz** [comment]
@c0 Thats correct. The object that is stored in redux is a smart lazy object that is able to traverse the falcor object graph. This is comes with tradeoffs though. As it creates an entire new object each time, which causes everything to rerender even when the data in that object hasn't changed.

I *think* `redux-falcor` can be made smarter and use the "version" property from falcor to fix this, but I haven't had the time to try it out yet.

**Comment by limscoder** [comment]
Question, which scenarios cause a `redux-falcor` component to re-render?

Do all `redux-falcor` components get re-rendered whenever any item in the cache is invalidated?
