### ISSUE TITLE
Does redux-falcor work with React Native?

### ISSUE THREAD

**Issue by MovingGifts** [ekosz/redux-falcor#19]
I am new to react native and starting a RN/Redux project and would like to use falcor for data.

I came across the redux thread where you created redux-falcor as an outcome.

The example I see is just for react. Is there a way to get redux-falcor working with RN?

**Comment by pickhardt** [comment]
Hey @MovingGifts, most JavaScript projects that work with node will work with React Native apps. The main thing to look for is whether the project uses some browser-specific functionality like `document.location` - in which case it won't be a good fit for RN.

I just tried redux-falcor with RN, and if you update your babelrc or install a few npm packages for babel, then it works. Just run these:
`npm install --save-dev babel-preset-es2015`
`npm install --save-dev babel-preset-stage-0`
`npm install --save-dev babel-preset-react`

And then it should work.
