### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by Whoaa512** [ekosz/redux-falcor#29]
I've read through https://supportedsource.org, but I didn't find any where stating how the pricing works in regards to versions.

For example, if Acme Company purchases a license in year 2016 for version 3.x.x of your library, is the pricing sticky for all time for that particular version of the library? By sticky I mean the pricing scale remains for that version for any year after, and would only increase as the employee size increases but would not increase because the pricing for a newer version of the library was different or because prices increase?

**Comment by pickhardt** [comment]
It's an annual license, so if you go into the next tier after you've already bought a license, you don't have to worry about the tier change until the time comes to get another license.
