### ISSUE TITLE
changing the model after instantiation

### ISSUE THREAD

**Issue by IwanKaramazow** [ekosz/redux-falcor#7]
This is merely a suggestion/enhancement. In my current scenario I need to change the ```headers``` from my ```HttpDataSource``` after the user logs in. 

Example:
```javascript
   const token = localStorage.getItem('token');
   const model = falcor.Model({
    source: new HttpDataSource('/falcor/model.json', {
      // Send the token as an Authorization header
      headers: {
        'Authorization': 'Bearer ' + token
      }
    })
  }).batch();

 // store creation, some code omitted for brevity
 applyMiddleware(thunk, createFalcorMiddleware(model)) 
```

The problem is, whenever a user logs in, the token stays ```null```, because the model has already been instantiated. If however a user doesn't log out when he closes the browser window, the token stays in localStorage and so the token in the ```Authorization``` will be the right one when he opens the webpage again.

Long story short, I need to change the ```DataSource headers``` after the ```Falcor Model``` has been instantiated. 

Quick solution:
```javascript
import { token }  from '../../path/to/initial/instantation/of/model';

function createFalcorMiddleware(falcor) {
  return function falcorMiddleware() {
    return next => action => {
      const { falcorPath, type, payload, ...rest } = action;

      if (token === null && localStorage.getItem('id_token') !== null)
        falcor = createFalcorModel(localStorage.getItem('id_token')); 
            // factory function that creates a batched falcor model with Authorization headers based on a token
           //  + replaces the current falcor model with a new one
    
   // rest of the middleware
}
```

No idea if this kind of  should functionality should be possible with redux-falcor...
It's more of an edge case. As for now, the only thing I came up with is creating a new model and replacing it in the middleware... Any thoughts?

**Comment by ekosz** [comment]
Looking at the [falcor-http-datasource readme](https://github.com/Netflix/falcor-http-datasource#readme) it looks like the `onBeforeRequest` hook maay be the best place to do this.

```js
class CustomSource extends HttpDataSource {
  onBeforeRequest(config) {
    const token = localStorage.getItem('id_token');
    if (token) config.headers['Authorization'] = 'Bearer ' + token;
  }
}

const model = falcor.Model({
  source: new CustomSource('/falcor/model.json')
}).batch();
```

Then for every request it will set token if it's available, otherwise it will not send the `Authorization` header. Do you think this will work for you?

**Comment by IwanKaramazow** [comment]
Thanks, the onBeforeRequest hook dit it! I didn't check the docs.. 😬
